# Generated by Django 5.0.4 on 2025-01-19 20:36

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=7, validators=[main.models.validate_colour])),
            ],
        ),
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)])),
                ('real_results', models.JSONField()),
                ('real_seats', models.JSONField()),
                ('parties', models.ManyToManyField(related_name='elections', to='main.party')),
            ],
            options={
                'verbose_name': 'Wybory',
                'verbose_name_plural': 'Wybory',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ElectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='election_data/', validators=[main.models.validate_geojson])),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.elections')),
                ('favoured_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoured_data', to='main.party')),
            ],
            options={
                'unique_together': {('elections', 'favoured_party')},
            },
        ),
    ]
