# Generated by Django 5.0.4 on 2025-01-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electiondata',
            options={'verbose_name': 'Election Data', 'verbose_name_plural': 'Election Data'},
        ),
        migrations.AlterModelOptions(
            name='elections',
            options={'ordering': ['-year'], 'verbose_name': 'Elections', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
    ]
