# Generated by Django 5.0.4 on 2025-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_electiondata_options_alter_elections_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiondata',
            name='seats',
            field=models.JSONField(null=True),
        ),
    ]
