# Generated by Django 5.0.4 on 2025-01-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_electiondata_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elections',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'Elections', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AddField(
            model_name='elections',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
